apiVersion: v1
kind: ConfigMap
metadata:
  name: account-config
  namespace: pfe-projet
data:
  app-config.yaml: |-
    service-name: accountService
    service-registry-address: consul-service:8500
    gateway-service-address: traefik-service
    kafka-address: kafka-service:9092
    database:
      host: mysql-service
      port: "3306"
      username: root
      password: Password@123
      dbname: erp_medical
      driver: mysql
    jwt:
      secret: skskjjekrko@103SSFk
    file:
      log-path: Logs
    server:
      port: 8000
      host: account-service
