apiVersion: v1
kind: ConfigMap
metadata:
  name: patient-config
  namespace: pfe-projet
data:
  app-config.yaml: |-
    service-name: patientService
    service-registry-address: consul-service:8500
    gateway-service-address: traefik-service
    kafka-address: kafka-service:9092
    database:
      host: mysql-service
      port: "3306"
      username: root
      password: Password@123
      dbname: erp_medical
      driver: mysql
    file:
      log-path: Logs
    server:
      port: 8001
      host: patient-service
