apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: pfe-projet
data:
  traefik-config.yaml: |-
    global:
      checkNewVersion: true
      sendAnonymousUsage: false

    log:
      level: "DEBUG"

    accessLog:
      filePath: "/var/log/traefik/access.log"
     

    entryPoints:
      web:
        address: ":80"
      traefik:
        address: ":8081"

    api:
      dashboard: true
      insecure: true

    providers:
      consulCatalog:
        prefix: "traefik"
        exposedByDefault: false
        defaultRule: "Host(`example.com/{{ .Name }}`)"
        endpoint:
          address: "consul-service:8500"
          scheme: "http"
