apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service-deployment
  namespace: pfe-projet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
      - name: appointment-service
        image: soufianeyemlahi/appointment-image:v3
        ports:
        - containerPort: 8003  
        volumeMounts:
          - name: config-volume
            mountPath: /app/application.yml  # Mount path for the YAML file
            subPath: app-config.yaml # Name of the YAML file inside the volume
            readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: appointment-config

