apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-deployment
  namespace: pfe-projet
spec:
  replicas: 1  # Set the desired number of replicas
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consul
          image: consul:latest
          ports:
            - containerPort: 8500  # Specify the port on which Consul UI/API listens
          command:
            - "consul"
            - "agent"
            - "-client=0.0.0.0"
            - "-dev"  # Specify the Consul agent options as per your requirements
          # Add other configuration, volumes, and volume mounts as needed
