apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service-deployment
  namespace: pfe-projet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
      - name: patient-service
        image: soufianeyemlahi/patient-service:v3
        ports:
        - containerPort: 8001
        volumeMounts:
          - name: config-volume
            mountPath: /app/application.yml  # Mount path for the YAML file
            subPath: app-config.yaml # Name of the YAML file inside the volume
            readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: patient-config

