apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-deployment
  namespace: pfe-projet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: traefik-config
      containers:
        - name: traefik
          image: traefik:v2.10.1
          volumeMounts:
            - name: config-volume
              mountPath: /etc/traefik/traefik.yaml
              subPath: traefik-config.yaml
          ports:
            - containerPort: 80
            - containerPort: 8081
