apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: pfe-projet
spec:
  selector:
    app: account-service
  ports:
    - protocol: TCP
      port: 8000  
      targetPort: 8000 
