apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  namespace: pfe-projet
spec:
  selector:
    app: appointment-service
  ports:
    - protocol: TCP
      port: 8003  
      targetPort: 8003
