apiVersion: v1
kind: Service
metadata:
  name: patient-service
  namespace: pfe-projet
spec:
  selector:
    app: patient-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
