apiVersion: v1
kind: Service
metadata:
  name: traefik-service
  namespace: pfe-projet
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 80
    - protocol: TCP
      name: traefik
      port: 8081
      targetPort: 8081
  selector:
    app: traefik
